#!/bin/bash
_TX_QUEUE_SIZE="tx_queue_size=1024"
_RX_QUEUE_SIZE="rx_queue_size=1024"
i=0
while [ $# -gt 0 ]
do
        case "$1" in
        -netdev|-device)
                args[i]="$1"
                (( i++ ))
                shift
                if [[ "$1" =~ "virtio-net-pci" ]]
                then
			args[i]=${1},${_RX_QUEUE_SIZE},${_TX_QUEUE_SIZE}
                        (( i++))
                        shift
                fi
                ;;
        *)
                args[i]="$1"
                (( i++ ))
                shift ;;
        esac
done
exec /usr/libexec/qemu-system-x86_64 "${args[@]}"
